sudo: false
language: python
python:
- '3.6'
install:
- pip install codecov
- pip install tox
- TOX_ENV=${TRAVIS_PYTHON_VERSION/[0-9].[0-9]/py${TRAVIS_PYTHON_VERSION/.}}
script: tox -e $TOX_ENV
after_success:
- codecov
before_cache:
- rm -rf $HOME/.cache/pip/log
cache:
  directories:
  - "$HOME/.cache/pip"
deploy:
  provider: pypi
  user: davidemoro
  password:
    secure: McFYaygzd6WOYyHCQf5ju+oGQcOpDgtNsJCdk61v15pJgE95anACo38PWIweQGrt7qwedODDZcFya8+6TtQbGp+x/Sy91WNdxKghYvI7ZJLb2yyn3sfy97n+Qh1F7gS5HMm5hqSp8pH3zjOgvKxe1yqigDIAoeufjZ+jvfLD/KPqJiFOZT3YBbdZexKL6VQ03KGaRjWBtmpRZoxT39oTGky8zuRjnLK+gZ6hcQEuLKnn39OgZbkkBv0yPITOAh/Zyrh/PTPhRCwaP2EQwdUCb7hQtecBA6+PS+QZzo6Bh/8WHZ5ITQL+jwqWE/nqLI3EichDykdb3MJDCjSbv8wN4LLhuFqklZ9tiEI2LbwdrN7hc1ynJ4PuDXNpy0hv6Sw6AzFonRpAbCFelM+Gsjs8tjXSBuzuaxLHvehyaAlOJ1WkqA2s0LXtXHBO+hhny9WpAGJdSpQxHivC2hGkv8WS08VIk/lnJT2LEdvtk0YIjK/aaG+hchz7ZSh3TcHrK3SHz32OsfUD78Th95nfs1QnltYZn2RvAxm6FA1yDCtfeJuGG+/kiJmRL58xiOcuqP0HYVYe7vUA9npNOKynkIhlj6x9LM+yCOaLBBIdwvWVTyZ1cP1nHyfaqVjY9W0AY0nJ9kwu6FSXE14B92nkedIEa0wLxaI9zKLmH0+ITIHGC0o=
  on:
    tags: true
    branch: master
    distributions: sdist bdist_wheel
    repo: davidemoro/play_selenium
